version: '2.2'

services:
  django:
    container_name: django
    extends:
      file: ./back/docker-compose.yml
      service: django
    expose:
    - "5959"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=beatitud.io
    command: /bin/sh -c "envsubst '$${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    volumes:
    - web:/data/web
    - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    - ./nginx/logs:/etc/nginx/logs
    - /root/certs-data/:/data/letsencrypt/:ro
    - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
    - django
 
  showcase:
    container_name: showcase
    extends:
      file: ./showcase/docker-compose.yml
      service: showcase

  showcase_angular:
    container_name: showcase_angular
    extends:
      file: ./showcase-angular/docker-compose.yml
      service: angular_showcase

  metricbeat:
    restart: always
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:6.5.2
    environment:
    - ELASTICSEARCH_HOST=search-beatitud-pxtyvfcgwra3pwfl34qhw4bejm.eu-west-3.es.amazonaws.com
    - KIBANA_HOST=search-beatitud-pxtyvfcgwra3pwfl34qhw4bejm.eu-west-3.es.amazonaws.com/_plugin/kibana
    - ELASTICSEARCH_USERNAME=""
    - ELASTICSEARCH_PASSWORD=""
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    ports:
    - "333:333"

volumes:
  nginx:
  django:
  showcase:
  metricbeat:
  web:
