version: '2.2'

services:
  django:
    extends:
      file: ./back/docker-compose.yml
      service: django

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    environment:
      - NGINX_HOST=beatitud.io # Host name
    command: /bin/sh -c "envsubst '$${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    volumes:
      - web:/data/web
      - web:/data/web:rw
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/logs:/etc/nginx/logs
      # Special to Beatitud
      - ./back:/data/back:ro
      # Certificat authentification
      - /root/certs-data/:/data/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

  metricbeat:
    restart: always
    image: docker.elastic.co/beats/metricbeat:6.5.2
    environment:
    - ELASTICSEARCH_HOST=search-beatitud-pxtyvfcgwra3pwfl34qhw4bejm.eu-west-3.es.amazonaws.com
    - KIBANA_HOST=search-beatitud-pxtyvfcgwra3pwfl34qhw4bejm.eu-west-3.es.amazonaws.com/_plugin/kibana
    - ELASTICSEARCH_USERNAME=""
    - ELASTICSEARCH_PASSWORD=""
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]

networks:
  elastic:
    external: true

volumes:
  nginx:
  django:
  metricbeat:
