version: '3.2'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=TO_BE_OVERWRITTEN # Host name
    command: /bin/sh -c "envsubst '$${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    volumes:
      - web:/data/web
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/logs:/etc/nginx/logs
      # Special to Beatitud
      - ./beatitud_back:/data/beatitud_back:ro

volumes:
  web: